### ISSUE TITLE
[BUG] <title>for c in content: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by SrikanthChellappa** [OpenBMB/MiniCPM-o#487]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

When I upload image and ask question and then follow it with a simple text thanking the assistant for response, I see the below error throwing up. For any default text only questions to the LLM, I pass an empty dummy image to align with MiniCPM prompting. It works well for text messages but after an image response it starts failing for text messages.

Error Trace
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\llava\lib\site-packages\gradio\queueing.py", line 541, in process_events
    response = await route_utils.call_process_api(
  File "C:\ProgramData\anaconda3\envs\llava\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\ProgramData\anaconda3\envs\llava\lib\site-packages\gradio\blocks.py", line 1928, in process_api
    result = await self.call_function(
  File "C:\ProgramData\anaconda3\envs\llava\lib\site-packages\gradio\blocks.py", line 1526, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\ProgramData\anaconda3\envs\llava\lib\site-packages\gradio\utils.py", line 657, in async_iteration
    return await iterator.__anext__()
  File "C:\ProgramData\anaconda3\envs\llava\lib\site-packages\gradio\utils.py", line 783, in asyncgen_wrapper
    response = await iterator.__anext__()
  File "C:\ProgramData\anaconda3\envs\llava\lib\site-packages\gradio\chat_interface.py", line 592, in _stream_fn
    first_response = await async_iteration(generator)
  File "C:\ProgramData\anaconda3\envs\llava\lib\site-packages\gradio\utils.py", line 657, in async_iteration
    return await iterator.__anext__()
  File "C:\ProgramData\anaconda3\envs\llava\lib\site-packages\gradio\utils.py", line 650, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\ProgramData\anaconda3\envs\llava\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\ProgramData\anaconda3\envs\llava\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\ProgramData\anaconda3\envs\llava\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\ProgramData\anaconda3\envs\llava\lib\site-packages\gradio\utils.py", line 633, in run_sync_iterator_async
    return next(iterator)
  File "E:\Generative AI\MEDLLM\Medical-Datasets\health-playground-4-miniclm-v3.py", line 134, in chat_llama3_8b
    res = model.chat(
  File "E:\huggingface\modules\transformers_modules\openbmb\MiniCPM-Llama3-V-2_5\ce88284a74330b80903e070ca57c6e232e5fb348\modeling_minicpmv.py", line 312, in chat
    for c in content:
TypeError: 'NoneType' object is not iterable

### 期望行为 | Expected Behavior

The assistant should respond to images and questions if a valid image is passed. In case, if an empty dummy image is passed, the assistant should be able to respond to text only prompts

### 复现方法 | Steps To Reproduce

1. Just pass an empty image and a simple Hello message to assistant. It responds
2. Add an image and ask a question around it to the assistant, it responds.
3. Now remove the above image and just say thank you to the assistant (with default empty image still passed), the assistant fails to respond with the above error message 

### 运行环境 | Environment

```Markdown
- OS:Windows11
- Python:3.10
- Transformers:4.43
- PyTorch:2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

**Comment by Cuiunbo** [comment]
please try our new finetuning code
