### ISSUE TITLE
[BUG] <title> errored out 

### ISSUE THREAD

**Issue by sheldon123z** [OpenBMB/MiniCPM-o#611]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

无法使用readme中提到的gradio打开就报错，显卡是A800,驱动都是最新的，并且重复进行了干净安装：

```
:~/exps/MiniCPM-V$ python web_demo_2.6.py --device cuda
/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/huggingface_hub/file_download.py:1142: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/huggingface_hub/file_download.py:1142: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Loading checkpoint shards: 100%|█████████████████████████████████████████| 4/4 [00:03<00:00,  1.24it/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Running on local URL:  http://0.0.0.0:8885
Running on public URL: https://11e6cd6656653d4b77.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/type_adapter.py", line 270, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/type_adapter.py", line 112, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/gradio/route_utils.py", line 733, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/gradio/route_utils.py", line 749, in simple_response
    await self.app(scope, receive, send)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/fastapi/routing.py", line 291, in app
    solved_result = await solve_dependencies(
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 656, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 881, in request_body_to_args
    fields_to_extract = get_cached_model_fields(first_field.type_)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/fastapi/_compat.py", line 657, in get_cached_model_fields
    return get_model_fields(model)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/fastapi/_compat.py", line 284, in get_model_fields
    return [
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/fastapi/_compat.py", line 285, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/fastapi/_compat.py", line 110, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/type_adapter.py", line 257, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/type_adapter.py", line 135, in wrapped
    return func(self, *args, **kwargs)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/type_adapter.py", line 277, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/type_adapter.py", line 95, in _get_schema
    schema = gen.generate_schema(type_)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 908, in _generate_schema_inner
    return self._annotated_schema(obj)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2028, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2107, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2189, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2185, in <lambda>
    lambda source, handler: handler(source)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2088, in inner_handler
    schema = self._generate_schema_inner(obj)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1029, in match_type
    return self._match_generic_type(obj, origin)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1058, in _match_generic_type
    return self._union_schema(obj)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1378, in _union_schema
    choices.append(self.generate_schema(arg))
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1038, in match_type
    return self._unknown_type_schema(obj)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 558, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/type_adapter.py", line 270, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/type_adapter.py", line 112, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/gradio/route_utils.py", line 733, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/gradio/route_utils.py", line 749, in simple_response
    await self.app(scope, receive, send)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/fastapi/routing.py", line 291, in app
    solved_result = await solve_dependencies(
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 656, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 881, in request_body_to_args
    fields_to_extract = get_cached_model_fields(first_field.type_)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/fastapi/_compat.py", line 657, in get_cached_model_fields
    return get_model_fields(model)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/fastapi/_compat.py", line 284, in get_model_fields
    return [
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/fastapi/_compat.py", line 285, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/fastapi/_compat.py", line 110, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/type_adapter.py", line 257, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/type_adapter.py", line 135, in wrapped
    return func(self, *args, **kwargs)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/type_adapter.py", line 277, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/type_adapter.py", line 95, in _get_schema
    schema = gen.generate_schema(type_)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 908, in _generate_schema_inner
    return self._annotated_schema(obj)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2028, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2107, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2189, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2185, in <lambda>
    lambda source, handler: handler(source)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2088, in inner_handler
    schema = self._generate_schema_inner(obj)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1029, in match_type
    return self._match_generic_type(obj, origin)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1058, in _match_generic_type
    return self._union_schema(obj)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1378, in _union_schema
    choices.append(self.generate_schema(arg))
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1038, in match_type
    return self._unknown_type_schema(obj)
  File "/home/zhengxiaodong/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 558, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.
```

<img width="1535" alt="image" src="https://github.com/user-attachments/assets/b7cbf895-7bbd-40a0-807a-cade98edfe86">

### 运行环境 | Environment

```Markdown
- OS: ubuntu 22.06


其他全部按照说明部署
```

**Comment by LDLINGLINGLING** [comment]
就报错来看，比较像是pydantic报错。能否试试更换pydantic版本

**Comment by qengli** [comment]
同样的问题，请问如何解决

**Comment by rikka0w0** [comment]
Same problem here on Ubuntu 24.04
