### ISSUE TITLE
[BUG] <title>TypeError: CPMTrainer.training_step() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by FrancisFan98** [OpenBMB/MiniCPM-o#698]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

[rank0]: Traceback (most recent call last):
[rank0]: File "/opt/MiniCPM-V-main/finetune/finetune.py", line 299, in
[rank0]: train()
[rank0]: File "/opt/MiniCPM-V-main/finetune/finetune.py", line 289, in train
[rank0]: trainer.train()
[rank0]: File "/root/miniconda3/envs/transformers/lib/python3.10/site-packages/transformers/trainer.py", line 2164, in train
[rank0]: return inner_training_loop(
[rank0]: File "/root/miniconda3/envs/transformers/lib/python3.10/site-packages/transformers/trainer.py", line 2524, in _inner_training_loop
[rank0]: tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank0]: TypeError: CPMTrainer.training_step() takes 3 positional arguments but 4 were given

I got this error when I tried to finetune the model, anyone knows how to solve it?

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by Bravo5542** [comment]
Same problem, recently appeared

**Comment by BugBugdie** [comment]
same, anybody solved?

**Comment by owl-10** [comment]
Same problem, recently appeared

**Comment by PhucNDA** [comment]
It is because of transformers version:
Transformers: 
transformers==4.47.1: vllms (used for inference)
transformers==4.40.0: trainable (used for training)

My current solution is swapping between these two. Looking forward to more feasible approaches...

**Comment by yuting89830** [comment]
Same problem
